name: release
on:
 push:
   tags:
     - "*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.20.x
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        distribution: goreleaser
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
